/* Automatic generated by NAppGUI Resource Compiler (nrc-v3528) */

#include "core.hxx"

__EXTERN_C

extern ResId IMAGE_JPG;
extern ResId IMAGE_PNG;

ResPack *all_respack(const char_t *locale);

__END_C
