# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adinortey/Developer/nappgui_sdk/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adinortey/Developer/currency-calculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adinortey/Developer/currency-calculator/CMakeFiles /home/adinortey/Developer/currency-calculator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adinortey/Developer/currency-calculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named casino

# Build rule for target.
casino: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 casino
.PHONY : casino

# fast build rule for target.
casino/fast:
	$(MAKE) $(MAKESILENT) -f demo/casino/CMakeFiles/casino.dir/build.make demo/casino/CMakeFiles/casino.dir/build
.PHONY : casino/fast

#=============================================================================
# Target rules for targets named HelloWorld

# Build rule for target.
HelloWorld: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HelloWorld
.PHONY : HelloWorld

# fast build rule for target.
HelloWorld/fast:
	$(MAKE) $(MAKESILENT) -f demo/hello/CMakeFiles/HelloWorld.dir/build.make demo/hello/CMakeFiles/HelloWorld.dir/build
.PHONY : HelloWorld/fast

#=============================================================================
# Target rules for targets named HelloCpp

# Build rule for target.
HelloCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HelloCpp
.PHONY : HelloCpp

# fast build rule for target.
HelloCpp/fast:
	$(MAKE) $(MAKESILENT) -f demo/hellocpp/CMakeFiles/HelloCpp.dir/build.make demo/hellocpp/CMakeFiles/HelloCpp.dir/build
.PHONY : HelloCpp/fast

#=============================================================================
# Target rules for targets named Die

# Build rule for target.
Die: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Die
.PHONY : Die

# fast build rule for target.
Die/fast:
	$(MAKE) $(MAKESILENT) -f demo/die/CMakeFiles/Die.dir/build.make demo/die/CMakeFiles/Die.dir/build
.PHONY : Die/fast

#=============================================================================
# Target rules for targets named Dice

# Build rule for target.
Dice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dice
.PHONY : Dice

# fast build rule for target.
Dice/fast:
	$(MAKE) $(MAKESILENT) -f demo/dice/CMakeFiles/Dice.dir/build.make demo/dice/CMakeFiles/Dice.dir/build
.PHONY : Dice/fast

#=============================================================================
# Target rules for targets named Bricks

# Build rule for target.
Bricks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bricks
.PHONY : Bricks

# fast build rule for target.
Bricks/fast:
	$(MAKE) $(MAKESILENT) -f demo/bricks/CMakeFiles/Bricks.dir/build.make demo/bricks/CMakeFiles/Bricks.dir/build
.PHONY : Bricks/fast

#=============================================================================
# Target rules for targets named Fractals

# Build rule for target.
Fractals: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fractals
.PHONY : Fractals

# fast build rule for target.
Fractals/fast:
	$(MAKE) $(MAKESILENT) -f demo/fractals/CMakeFiles/Fractals.dir/build.make demo/fractals/CMakeFiles/Fractals.dir/build
.PHONY : Fractals/fast

#=============================================================================
# Target rules for targets named Bode

# Build rule for target.
Bode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bode
.PHONY : Bode

# fast build rule for target.
Bode/fast:
	$(MAKE) $(MAKESILENT) -f demo/bode/CMakeFiles/Bode.dir/build.make demo/bode/CMakeFiles/Bode.dir/build
.PHONY : Bode/fast

#=============================================================================
# Target rules for targets named Products

# Build rule for target.
Products: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Products
.PHONY : Products

# fast build rule for target.
Products/fast:
	$(MAKE) $(MAKESILENT) -f demo/products/CMakeFiles/Products.dir/build.make demo/products/CMakeFiles/Products.dir/build
.PHONY : Products/fast

#=============================================================================
# Target rules for targets named GuiHello

# Build rule for target.
GuiHello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GuiHello
.PHONY : GuiHello

# fast build rule for target.
GuiHello/fast:
	$(MAKE) $(MAKESILENT) -f howto/guihello/CMakeFiles/GuiHello.dir/build.make howto/guihello/CMakeFiles/GuiHello.dir/build
.PHONY : GuiHello/fast

#=============================================================================
# Target rules for targets named DrawHello

# Build rule for target.
DrawHello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DrawHello
.PHONY : DrawHello

# fast build rule for target.
DrawHello/fast:
	$(MAKE) $(MAKESILENT) -f howto/drawhello/CMakeFiles/DrawHello.dir/build.make howto/drawhello/CMakeFiles/DrawHello.dir/build
.PHONY : DrawHello/fast

#=============================================================================
# Target rules for targets named Col2dHello

# Build rule for target.
Col2dHello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Col2dHello
.PHONY : Col2dHello

# fast build rule for target.
Col2dHello/fast:
	$(MAKE) $(MAKESILENT) -f howto/col2dhello/CMakeFiles/Col2dHello.dir/build.make howto/col2dhello/CMakeFiles/Col2dHello.dir/build
.PHONY : Col2dHello/fast

#=============================================================================
# Target rules for targets named DrawImg

# Build rule for target.
DrawImg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DrawImg
.PHONY : DrawImg

# fast build rule for target.
DrawImg/fast:
	$(MAKE) $(MAKESILENT) -f howto/drawimg/CMakeFiles/DrawImg.dir/build.make howto/drawimg/CMakeFiles/DrawImg.dir/build
.PHONY : DrawImg/fast

#=============================================================================
# Target rules for targets named UrlImg

# Build rule for target.
UrlImg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UrlImg
.PHONY : UrlImg

# fast build rule for target.
UrlImg/fast:
	$(MAKE) $(MAKESILENT) -f howto/urlimg/CMakeFiles/UrlImg.dir/build.make howto/urlimg/CMakeFiles/UrlImg.dir/build
.PHONY : UrlImg/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Bode"
	@echo "... Bricks"
	@echo "... Col2dHello"
	@echo "... Dice"
	@echo "... Die"
	@echo "... DrawHello"
	@echo "... DrawImg"
	@echo "... Fractals"
	@echo "... GuiHello"
	@echo "... HelloCpp"
	@echo "... HelloWorld"
	@echo "... Products"
	@echo "... UrlImg"
	@echo "... casino"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

