/* Automatic generated by NAppGUI Resource Compiler (nrc-v3528) */

#include "core.hxx"

__EXTERN_C

/* Messages */
extern ResId ABOUT;
extern ResId PREFERENCES;
extern ResId QUIT;
extern ResId OPEN_DATABASE;
extern ResId SAVE_DATABASE;
extern ResId CLOSE_DATABASE;
extern ResId EXIT;
extern ResId FIRST_RECORD;
extern ResId BACK_RECORD;
extern ResId NEXT_RECORD;
extern ResId LAST_RECORD;
extern ResId VIEW_FORM;
extern ResId VIEW_TABLE;
extern ResId LOGIN_PANEL;
extern ResId LOGOUT;
extern ResId ABOUT_NAPPGUI;
extern ResId FILEM;
extern ResId NAVIGATE;
extern ResId VIEW;
extern ResId SERVER;
extern ResId HELP;

/* Files */
extern ResId ABOUT_PNG;
extern ResId ACCESS_PNG;
extern ResId BACK_PNG;
extern ResId BACK16_PNG;
extern ResId BACK_RED_PNG;
extern ResId BLACK_PNG;
extern ResId BLUE_PNG;
extern ResId BUILDING_JPG;
extern ResId CAR_JPG;
extern ResId CLOSE_PNG;
extern ResId DISK12_PNG;
extern ResId DISK16_PNG;
extern ResId DISK24_PNG;
extern ResId DISK32_PNG;
extern ResId DISK64_PNG;
extern ResId DISK8_PNG;
extern ResId DOCUMENT_PNG;
extern ResId EDIT16_PNG;
extern ResId EDIT24_PNG;
extern ResId EDIT32_PNG;
extern ResId EDIT64_PNG;
extern ResId ERROR16_PNG;
extern ResId ERROR24_PNG;
extern ResId ERROR32_PNG;
extern ResId ERROR64_PNG;
extern ResId EXCEL_PNG;
extern ResId EXIT_PNG;
extern ResId FIRST_PNG;
extern ResId FIRST16_PNG;
extern ResId FIRST_RED_PNG;
extern ResId FOLDER16_PNG;
extern ResId FOLDER24_PNG;
extern ResId FOLDER32_PNG;
extern ResId FOLDER64_PNG;
extern ResId GREEN_PNG;
extern ResId ITALY_PNG;
extern ResId JAPAN_PNG;
extern ResId JPG_PNG;
extern ResId LAPTOP_JPG;
extern ResId LAST_PNG;
extern ResId LAST16_PNG;
extern ResId LAST_RED_PNG;
extern ResId LOGIN_PNG;
extern ResId LOGOUT_PNG;
extern ResId NEXT_PNG;
extern ResId NEXT16_PNG;
extern ResId NEXT_RED_PNG;
extern ResId OPEN_PNG;
extern ResId PDF_PNG;
extern ResId PLAY_PNG;
extern ResId PLAY_RED_PNG;
extern ResId PLUS16_PNG;
extern ResId PLUS24_PNG;
extern ResId PLUS32_PNG;
extern ResId PLUS64_PNG;
extern ResId PORTUGAL_PNG;
extern ResId POWERPOINT_PNG;
extern ResId RED_PNG;
extern ResId REFRESH_PNG;
extern ResId REFRESH_RED_PNG;
extern ResId RESTORE16_PNG;
extern ResId RETRY_PNG;
extern ResId RUSSIA_PNG;
extern ResId SAVE_PNG;
extern ResId SEARCH16_PNG;
extern ResId SEARCH24_PNG;
extern ResId SEARCH32_PNG;
extern ResId SEARCH64_PNG;
extern ResId SETTINGS_PNG;
extern ResId SPAIN_PNG;
extern ResId UKING_PNG;
extern ResId VIETNAM_PNG;
extern ResId WARNING_PNG;
extern ResId WHITE_PNG;
extern ResId WORD_PNG;
extern ResId YELLOW_PNG;
extern ResId TEXTVIEW_RTF;

ResPack *res_respack(const char_t *locale);

__END_C
