/* Automatic generated by NAppGUI Resource Compiler (nrc-v3528) */

#include "core.hxx"

__EXTERN_C

/* Messages */
extern ResId TWIN_TITLE;
extern ResId TWIN_FIRST;
extern ResId TWIN_BACK;
extern ResId TWIN_NEXT;
extern ResId TWIN_LAST;
extern ResId TWIN_ADD;
extern ResId TWIN_DEL;
extern ResId TWIN_FILTER_DESC;
extern ResId TWIN_FILTER;
extern ResId TWIN_SETTINGS_PANEL;
extern ResId TWIN_CODE;
extern ResId TWIN_TYPE_CODE;
extern ResId TWIN_DESC;
extern ResId TWIN_TYPE_DESC;
extern ResId TWIN_CPU;
extern ResId TWIN_GPU;
extern ResId TWIN_HDD;
extern ResId TWIN_SCD;
extern ResId TWIN_TYPE_PRICE;
extern ResId TWIN_TYPE;
extern ResId TWIN_PRICE;
extern ResId TWIN_USER;
extern ResId TWIN_PASS;
extern ResId TWIN_LOGIN_MSG;
extern ResId TWIN_LOGIN;
extern ResId TWIN_LOGOUT;
extern ResId TWIN_SETLANG;
extern ResId WAIT_LOGIN;
extern ResId IN_LOGIN;
extern ResId OK_LOGIN;
extern ResId ERR_CONNECT;
extern ResId ERR_JSON;
extern ResId ERR_ACCESS;
extern ResId TMEN_ABOUT;
extern ResId TMEN_PREFERS;
extern ResId TMEN_QUIT;
extern ResId TMEN_IMPORT;
extern ResId TMEN_EXPORT;
extern ResId TMEN_EXIT;
extern ResId TMEN_LOGIN_PANEL;
extern ResId TMEN_LOGIN;
extern ResId TMEN_LOGOUT;
extern ResId TMEN_FILE;
extern ResId TMEN_NAVIGATE;
extern ResId TMEN_FIRST;
extern ResId TMEN_BACK;
extern ResId TMEN_NEXT;
extern ResId TMEN_LAST;
extern ResId TMEN_VIEW;
extern ResId TMEN_SERVER;
extern ResId TMEN_HELP;
extern ResId LANGUAGE;
extern ResId ENGLISH;
extern ResId SPANISH;
extern ResId PORTUGUESE;
extern ResId ITALIAN;
extern ResId VIETNAMESE;
extern ResId RUSSIAN;
extern ResId JAPANESE;

/* Files */
extern ResId ABOUT_PNG;
extern ResId ADD_PNG;
extern ResId BACK_PNG;
extern ResId BACK16_PNG;
extern ResId BACK16D_PNG;
extern ResId BACKD_PNG;
extern ResId EDIT_PNG;
extern ResId ERROR_PNG;
extern ResId EXIT_PNG;
extern ResId FIRST_PNG;
extern ResId FIRST16_PNG;
extern ResId FIRST16D_PNG;
extern ResId FIRSTD_PNG;
extern ResId ITALY_PNG;
extern ResId JAPAN_PNG;
extern ResId LAST_PNG;
extern ResId LAST16_PNG;
extern ResId LAST16D_PNG;
extern ResId LASTD_PNG;
extern ResId LOGIN16_PNG;
extern ResId LOGOUT16_PNG;
extern ResId LOGOUT16D_PNG;
extern ResId MINUS_PNG;
extern ResId NEXT_PNG;
extern ResId NEXT16_PNG;
extern ResId NEXT16D_PNG;
extern ResId NEXTD_PNG;
extern ResId NOIMAGE_PNG;
extern ResId OK_PNG;
extern ResId OPEN_PNG;
extern ResId PORTUGAL_PNG;
extern ResId RUSSIA_PNG;
extern ResId SAVE_PNG;
extern ResId SAVED_PNG;
extern ResId SETTINGS_PNG;
extern ResId SETTINGS16_PNG;
extern ResId SPAIN_PNG;
extern ResId SPIN_GIF;
extern ResId USA_PNG;
extern ResId USER_PNG;
extern ResId VIETNAM_PNG;

ResPack *res_gui_respack(const char_t *locale);

__END_C
