/* Automatic generated by NAppGUI Resource Compiler (nrc-v3528) */

#include "res_gui.h"
#include "respackh.h"

/*---------------------------------------------------------------------------*/

ResId TWIN_TITLE = "N23R3C75::res_gui::0";
ResId TWIN_FIRST = "N23R3C75::res_gui::1";
ResId TWIN_BACK = "N23R3C75::res_gui::2";
ResId TWIN_NEXT = "N23R3C75::res_gui::3";
ResId TWIN_LAST = "N23R3C75::res_gui::4";
ResId TWIN_ADD = "N23R3C75::res_gui::5";
ResId TWIN_DEL = "N23R3C75::res_gui::6";
ResId TWIN_FILTER_DESC = "N23R3C75::res_gui::7";
ResId TWIN_FILTER = "N23R3C75::res_gui::8";
ResId TWIN_SETTINGS_PANEL = "N23R3C75::res_gui::9";
ResId TWIN_CODE = "N23R3C75::res_gui::10";
ResId TWIN_TYPE_CODE = "N23R3C75::res_gui::11";
ResId TWIN_DESC = "N23R3C75::res_gui::12";
ResId TWIN_TYPE_DESC = "N23R3C75::res_gui::13";
ResId TWIN_CPU = "N23R3C75::res_gui::14";
ResId TWIN_GPU = "N23R3C75::res_gui::15";
ResId TWIN_HDD = "N23R3C75::res_gui::16";
ResId TWIN_SCD = "N23R3C75::res_gui::17";
ResId TWIN_TYPE_PRICE = "N23R3C75::res_gui::18";
ResId TWIN_TYPE = "N23R3C75::res_gui::19";
ResId TWIN_PRICE = "N23R3C75::res_gui::20";
ResId TWIN_USER = "N23R3C75::res_gui::21";
ResId TWIN_PASS = "N23R3C75::res_gui::22";
ResId TWIN_LOGIN_MSG = "N23R3C75::res_gui::23";
ResId TWIN_LOGIN = "N23R3C75::res_gui::24";
ResId TWIN_LOGOUT = "N23R3C75::res_gui::25";
ResId TWIN_SETLANG = "N23R3C75::res_gui::26";
ResId WAIT_LOGIN = "N23R3C75::res_gui::27";
ResId IN_LOGIN = "N23R3C75::res_gui::28";
ResId OK_LOGIN = "N23R3C75::res_gui::29";
ResId ERR_CONNECT = "N23R3C75::res_gui::30";
ResId ERR_JSON = "N23R3C75::res_gui::31";
ResId ERR_ACCESS = "N23R3C75::res_gui::32";
ResId TMEN_ABOUT = "N23R3C75::res_gui::33";
ResId TMEN_PREFERS = "N23R3C75::res_gui::34";
ResId TMEN_QUIT = "N23R3C75::res_gui::35";
ResId TMEN_IMPORT = "N23R3C75::res_gui::36";
ResId TMEN_EXPORT = "N23R3C75::res_gui::37";
ResId TMEN_EXIT = "N23R3C75::res_gui::38";
ResId TMEN_LOGIN_PANEL = "N23R3C75::res_gui::39";
ResId TMEN_LOGIN = "N23R3C75::res_gui::40";
ResId TMEN_LOGOUT = "N23R3C75::res_gui::41";
ResId TMEN_FILE = "N23R3C75::res_gui::42";
ResId TMEN_NAVIGATE = "N23R3C75::res_gui::43";
ResId TMEN_FIRST = "N23R3C75::res_gui::44";
ResId TMEN_BACK = "N23R3C75::res_gui::45";
ResId TMEN_NEXT = "N23R3C75::res_gui::46";
ResId TMEN_LAST = "N23R3C75::res_gui::47";
ResId TMEN_VIEW = "N23R3C75::res_gui::48";
ResId TMEN_SERVER = "N23R3C75::res_gui::49";
ResId TMEN_HELP = "N23R3C75::res_gui::50";
ResId LANGUAGE = "N23R3C75::res_gui::51";
ResId ENGLISH = "N23R3C75::res_gui::52";
ResId SPANISH = "N23R3C75::res_gui::53";
ResId PORTUGUESE = "N23R3C75::res_gui::54";
ResId ITALIAN = "N23R3C75::res_gui::55";
ResId VIETNAMESE = "N23R3C75::res_gui::56";
ResId RUSSIAN = "N23R3C75::res_gui::57";
ResId JAPANESE = "N23R3C75::res_gui::58";
ResId ABOUT_PNG = "N23R3C75::res_gui::59";
ResId ADD_PNG = "N23R3C75::res_gui::60";
ResId BACK_PNG = "N23R3C75::res_gui::61";
ResId BACK16_PNG = "N23R3C75::res_gui::62";
ResId BACK16D_PNG = "N23R3C75::res_gui::63";
ResId BACKD_PNG = "N23R3C75::res_gui::64";
ResId EDIT_PNG = "N23R3C75::res_gui::65";
ResId ERROR_PNG = "N23R3C75::res_gui::66";
ResId EXIT_PNG = "N23R3C75::res_gui::67";
ResId FIRST_PNG = "N23R3C75::res_gui::68";
ResId FIRST16_PNG = "N23R3C75::res_gui::69";
ResId FIRST16D_PNG = "N23R3C75::res_gui::70";
ResId FIRSTD_PNG = "N23R3C75::res_gui::71";
ResId ITALY_PNG = "N23R3C75::res_gui::72";
ResId JAPAN_PNG = "N23R3C75::res_gui::73";
ResId LAST_PNG = "N23R3C75::res_gui::74";
ResId LAST16_PNG = "N23R3C75::res_gui::75";
ResId LAST16D_PNG = "N23R3C75::res_gui::76";
ResId LASTD_PNG = "N23R3C75::res_gui::77";
ResId LOGIN16_PNG = "N23R3C75::res_gui::78";
ResId LOGOUT16_PNG = "N23R3C75::res_gui::79";
ResId LOGOUT16D_PNG = "N23R3C75::res_gui::80";
ResId MINUS_PNG = "N23R3C75::res_gui::81";
ResId NEXT_PNG = "N23R3C75::res_gui::82";
ResId NEXT16_PNG = "N23R3C75::res_gui::83";
ResId NEXT16D_PNG = "N23R3C75::res_gui::84";
ResId NEXTD_PNG = "N23R3C75::res_gui::85";
ResId NOIMAGE_PNG = "N23R3C75::res_gui::86";
ResId OK_PNG = "N23R3C75::res_gui::87";
ResId OPEN_PNG = "N23R3C75::res_gui::88";
ResId PORTUGAL_PNG = "N23R3C75::res_gui::89";
ResId RUSSIA_PNG = "N23R3C75::res_gui::90";
ResId SAVE_PNG = "N23R3C75::res_gui::91";
ResId SAVED_PNG = "N23R3C75::res_gui::92";
ResId SETTINGS_PNG = "N23R3C75::res_gui::93";
ResId SETTINGS16_PNG = "N23R3C75::res_gui::94";
ResId SPAIN_PNG = "N23R3C75::res_gui::95";
ResId SPIN_GIF = "N23R3C75::res_gui::96";
ResId USA_PNG = "N23R3C75::res_gui::97";
ResId USER_PNG = "N23R3C75::res_gui::98";
ResId VIETNAM_PNG = "N23R3C75::res_gui::99";

/*---------------------------------------------------------------------------*/

ResPack *res_gui_respack(const char_t *locale)
{
    return respack_packed("res_gui", locale);
}
