/* Automatic generated by NAppGUI Resource Compiler (nrc-v3528) */

#include "core.hxx"

__EXTERN_C

extern ResId MONKEY_GIF;
extern ResId ZOMBIE_PNG;

ResPack *allres_respack(const char_t *locale);

__END_C
